module.exports = [
    'Rati pickea Reksai',
    'Rati feedea al mid',
    'Piedra es un minion',
    'Piedra pierde linea',
    'Alguien tira Panic Flash',
    'Dragon steal',
    'Baron steal',
    'Rati pickea Zoe',
    'Emma se queda en modo torreta',
    'Piedra no usa tp',
    'Katalisin combo',
    'Emma se tiltea por ir supp',
    'Emma pickea Bron',
    'Emma saca pick secreto y trollea',
    'Emma saca pick secreto y carrea',
    'Emma va ADC',
    'MM y Emma botlane',
    'Banean Kata',
    'Banean Shen',
    'Banean Twitch',
    'Banean Zoe',
    'Banean Reksai',
    'Banean al poni chipeado',
    'Fox pickea al poni chipeado',
    'Fox carrea',
    'Piedra pickea Rakan',
    'Piedra tiltea a Emma',
    'Banean Cassio',
    'Banean Bron',
    'MM tiene packetloss',
    'MM se feedea',
    'Pickeamos Caitlyn',
    'Perdemos en la primera ronda',
    'Perdemos clash',
    'Ganamos clash',
    'Emparejamiento contra diamantes',
    'a Piedra se le cae la puerta',
    'Rati nos vende',
    'Piedra nos vende',
    'Alguien hace misspick',
    'Alguien no intercambia a tiempo',
    'Alguien lleva las runas equivocadas',
    'Piedra trollea',
    'Nos hacen invade',
    'Hacemos invade',
    'Alguien muere minuto 2',
    'Nos stompean',
    'Stompeamos',
]
