module.exports = [
    'Piedra es un minion',
    'Piedra pierde linea',
    'Alguien tira Panic Flash',
    'Dragon steal',
    'Baron steal',
    'Emma se queda en modo torreta',
    'Piedra no usa tp',
    'Katalisin combo',
    'Emma se tiltea por ir supp',
    'Emma pickea Bron',
    'Emma saca pick secreto y trollea',
    'Emma saca pick secreto y carrea',
    'Emma va ADC',
    'MM y Emma botlane',
    'Banean Kata',
    'Banean Twitch',
    'Piedra pickea Rakan',
    'Piedra tiltea a Emma',
    'Banean Cassio',
    'Banean Bron',
    'MM tiene packetloss',
    'MM se feedea',
    'Pickeamos Caitlyn',
    'Perdemos en la primera ronda',
    'Perdemos clash',
    'Ganamos clash',
    'Emparejamiento contra diamantes',
    'a Piedra se le cae la puerta',
    'Piedra nos vende',
    'Alguien hace misspick',
    'Alguien no intercambia a tiempo',
    'Alguien lleva las runas equivocadas',
    'Piedra trollea',
    'Nos hacen invade',
    'Hacemos invade',
    'Alguien muere minuto 2',
    'Nos stompean',
    'Stompeamos',
    'Dranca va corki',
    'Dranca va malza'
    'Banean malza',
    'Banean Kindred',
    'Larm va Diego',
    'Banean Diego',
    'Emma va gwen',
    'Ganamos por default',
    'Kata tuich combo',
    'Dranca trollea',
    'Tuich supp',
]
